sudo: required
services:
  - docker

before_install:
  - docker build -t vipulvinayak/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true vipulvinayak/docker-react npm run test -- --coverage